-- Working Neon Import - 40 columns exactly
-- This will add conflict data to fix the State Comparison chart

-- Borno State (state_id = 3) - Boko Haram activity
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-01', 3, 1, 1, 3, 57, 'Kondori', 0, 0, 4, 0, 0, NULL, 0, 0, 3, 0, 0, 0, 'No', 0, 0, 3, 4, NULL, 'attack by Boko Haram', 'attack', NULL, 'Confirmed by military intelligence', '1', 'https://www.sunnewsonline.com/4-killed-3-injured-as-boko-haram-unleash-mayhem-on-borno-village/', NULL, NULL, 'Sources: The Sun', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-02', 3, 1, 1, 3, 778, 'Kwabula', 0, 0, 2, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 3, 4, NULL, 'attack by Boko Haram', 'attack', NULL, NULL, '1', 'https://dailypost.ng/2020/06/02/boko-haram-13-killed-in-borno/', NULL, NULL, 'Sources: Daily post', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-04', 3, 1, 1, 3, 44, 'Banki', 0, 0, 75, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 3, NULL, 'Troops killed Boko Haram fighters in armed clash', 'armed clash', NULL, 'Confirmed by DMO Coordinator', '1', 'https://punchng.com/troops-killed-shekaus-aides-72-boko-haram-fighters-dhq/', NULL, NULL, 'Sources: Punch', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Kaduna State (state_id = 15) - Banditry
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-01', 2, 1, 3, 15, 263, 'Kaya', 14, 0, 0, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 5, 5, 22, 'attack by bandits', 'attack', NULL, 'Confirmed by state authorities', '1', 'https://www.premiumtimesng.com/news/headlines/434693-bandits-attack-kaduna-community-kill-14.html', NULL, NULL, 'Sources: Premium Times', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-01', 2, 1, 3, 15, 263, 'Kadai', 9, 0, 0, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 2, 22, 'encounter between security forces and bandits', 'armed clash', NULL, 'incidence announced by DMO Coordinator', '1', 'https://www.thisdaylive.com/index.php/2020/10/11/bandits-kill-12-in-kaduna-communities/', NULL, NULL, 'Sources: Thisday', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-01', 2, 1, 3, 15, 340, 'Shau', 0, 0, 8, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 2, 4, 22, 'Bandits kill Imam and 7 others', 'attack', NULL, 'Confirmed by state police', '1', 'https://www.thisdaylive.com/index.php/2020/10/13/bandits-kill-imam-12-others-in-katsina-niger-communities/', NULL, NULL, 'Sources: Thisday', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-08', 2, 1, 3, 15, 268, 'Kachia Forest', 0, 0, 70, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 2, 22, 'encounter between security forces and bandits', 'armed clash', NULL, 'incidence reported by DMO Cordinator', '1', 'https://www.vanguardngr.com/2020/06/troops-eliminate-70-bandits-in-kachia-forest/', NULL, NULL, 'Sources: Vanguard', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Katsina State (state_id = 17) - Banditry
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-01', 2, 1, 3, 17, 775, 'Yantumaki', 0, 0, 1, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 5, 5, 22, 'attack by bandits', 'attack', NULL, 'Confirmed by state police', '1', 'https://guardian.ng/news/bandits-kill-traditional-ruler-in-katsina/', NULL, NULL, 'Sources: The Guardian', NULL, 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-04', 2, 1, 3, 17, 349, 'Dagwarwa', 0, 0, 2, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 2, 4, 22, 'attack by bandits', 'attack', NULL, NULL, '1', 'https://guardian.ng/news/bandits-kill-two-in-katsina/', NULL, NULL, 'Sources: The Guardian', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-08', 2, 1, 3, 17, 268, 'Kachia Forest', 0, 0, 70, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 2, 22, 'encounter between security forces and bandits', 'armed clash', NULL, 'incidence reported by DMO Cordinator', '1', 'https://www.vanguardngr.com/2020/06/troops-eliminate-70-bandits-in-kachia-forest/', NULL, NULL, 'Sources: Vanguard', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Zamfara State (state_id = 20) - Banditry
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-01', 2, 1, 3, 20, 776, 'Birnin Kogo', 0, 0, 4, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 2, 22, 'encounter between security forces and bandits', 'armed clash', NULL, 'incidence announced by DMO Coordinator', '1', 'https://www.dailytrust.com.ng/troops-kill-4-bandits-in-zamfara.html', NULL, NULL, 'Sources: Daily trust', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-07', 2, 1, 3, 20, 776, 'Warnu', 0, 0, 2, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 2, 22, 'Nigerian troops kill 2 bandits in Zamfara', 'armed clash', NULL, 'Confirmed by Defence Media Operations', '1', 'https://www.premiumtimesng.com/regional/nwest/396559-nigerian-troops-kill-arrest-more-bandits-in-zamfara-official.html', NULL, NULL, 'Sources: Premium Times', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-07', 2, 1, 3, 20, 776, 'Yauyau and Zandam', 0, 0, 3, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 2, 22, 'Nigerian troops kill 3 bandits in Zamfara', 'armed clash', NULL, 'Confirmed by Defence Media Operations', '1', 'https://www.premiumtimesng.com/regional/nwest/396559-nigerian-troops-kill-arrest-more-bandits-in-zamfara-official.html', NULL, NULL, 'Sources: Premium Times', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Benue State (state_id = 7) - Farmers-Herders clashes
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-02', 6, 1, 2, 7, 126, 'Itakpa', 0, 0, 13, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 8, 4, 22, 'attacked by Fulani herdsmen', 'attack', NULL, 'Confirmed by state police', '1', 'http://saharareporters.com/2020/06/02/suspected-herdsmen-attack-kill-residents-benue-community', NULL, NULL, 'Sources: Saharareporters', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Plateau State (state_id = 12) - Communal violence
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-01', 12, 1, 1, 12, 57, 'Kondori', 0, 0, 4, 0, 0, NULL, 0, 0, 3, 0, 0, 0, 'No', 0, 0, 3, 4, NULL, 'attack by Boko Haram', 'armed clash', NULL, 'Confirmed by military intelligence', '1', 'https://www.sunnewsonline.com/4-killed-3-injured-as-boko-haram-unleash-mayhem-on-borno-village/', NULL, NULL, 'Sources: The Sun', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Rivers State (state_id = 22) - Political violence
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-10-12', 7, 1, 6, 22, 673, 'Surulere', 0, 0, 1, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 19, 22, 'Police attack EndSARS protesters in Surulere', 'attack', NULL, 'Confirmed by traditional chief', '1', 'https://guardian.ng/news/police-attack-endsars-protesters-in-surulere-kill-one/', NULL, NULL, 'Sources: The Guardian', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-10-13', 7, 1, 6, 22, 791, 'Ogbomosho', 0, 0, 3, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 21, 19, 22, 'Killed during protest', 'armed clash', NULL, 'Confirmed by traditional chief', '1', 'https://www.premiumtimesng.com/regional/sssouth-west/420389-endsars-three-more-people-killed-during-protests-in-ogbomoso.html', NULL, NULL, 'Sources: Premium Times', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Cross River State (state_id = 29) - Cult clashes
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-08-04', 4, 1, 4, 29, 556, 'Ikot Offiong Ambi', 0, 0, 5, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 24, 24, 22, 'cult clash', 'attack', NULL, 'police deployed to maintain peace', '1', 'https://guardian.ng/news/five-feared-killed-in-cross-river-cult-clash/', NULL, NULL, 'Sources: Nigerian Tribune', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Oyo State (state_id = 32) - Farmers-Herders clashes
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-02', 6, 1, 6, 32, 777, 'Egbo', 0, 0, 2, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 8, 23, 22, 'Farmers attacked by herdsmen in Oyo State', 'attack', NULL, 'Confirmed by state police', '1', 'https://tribuneonlineng.com/how-three-farmers-were-killed-by-suspected-herdsmen-in-ibadan/', NULL, NULL, 'Sources: Nigerian Tribune', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL),
('2020-06-02', 6, 1, 6, 32, 777, 'Babalola', 0, 0, 1, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 8, 23, 22, 'Farmer attacked by herdsmen in Oyo State', 'attack', NULL, 'Confirmed by state police', '1', 'https://tribuneonlineng.com/how-three-farmers-were-killed-by-suspected-herdsmen-in-ibadan/', NULL, NULL, 'Sources: Nigerian Tribune', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Delta State (state_id = 24) - Political violence
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-02', 3, 1, 6, 24, 779, 'Ibeshe', 0, 0, 2, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 4, 4, 22, 'attack over representation between traditional class and youths', 'attack', NULL, 'Confirmed by military intelligence', '1', 'https://www.vanguardngr.com/2020/06/two-dead-others-injured-as-monarch-escapes-lynching-by-ibeshe-youths/', NULL, NULL, 'Sources: Vanguard', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Imo State (state_id = 31) - Security forces clash
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-07', 8, 1, 5, 31, 637, 'Gio', 0, 0, NULL, 0, 0, 1, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 7, 21, 22, 'NSDC officer killed by gunmen suspected to be oil thieves', 'armed clash', NULL, 'incidence announced by agency spokesperson', '1', 'https://www.premiumtimesng.com/news/top-news/396570-gunmen-kill-another-nigerian-civil-defence-officer-third-in-two-months.html', NULL, NULL, 'Sources: Premium Times', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);

-- Ebonyi State (state_id = 28) - Communal clash
INSERT INTO conflicts (incidence_date, conflict_type_id, country_id, region_id, state_id, lga_id, community, civilian_death_male, civilian_death_female, civilian_death_unknown, security_death_male, security_death_female, security_death_unknown, injured_male, injured_female, injured_unknown, kidnapped_male, kidnapped_female, kidnapped_unknown, displaced_persons, displaced_male, displaced_female, actor_1, actor_2, actor_3, description, action, highway_roads_water, confirmation_verification, verification_level, source_url, source_contact_details, source_contact_pictures, source_metadata, data_source, reporter_id, created_at, updated_at, deleted_at) VALUES
('2020-06-07', 3, 1, 4, 28, 470, 'Ishinkwo', 0, 0, 4, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, 'No', 0, 0, 5, 5, 22, '4 Persons Killed In Ebonyi Communal Clash', 'attack', NULL, 'Eye Witness', '1', 'http://saharareporters.com/2020/06/07/four-persons-killed-ebonyi-communal-clash', NULL, NULL, 'Sources: Saharareporters', 'Secondary', 1, '2026-01-25 11:22:30', '2026-01-25 11:22:30', NULL);
