#!/usr/bin/env python3
"""
Script to toggle authentication feature flag for demos
Usage: python scripts/toggle_auth.py [--enable|--disable] [--user-id USER_ID]
"""

import os
import sys
import argparse
from pathlib import Path

# Get project root directory
PROJECT_ROOT = Path(__file__).parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

def read_env_file():
    """Read current .env file"""
    env_vars = {}
    if ENV_FILE.exists():
        with open(ENV_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key] = value
    return env_vars

def write_env_file(env_vars):
    """Write to .env file"""
    with open(ENV_FILE, 'w') as f:
        f.write("# Nigeria Conflict Tracker Environment Variables\n")
        f.write("# Generated by toggle_auth.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")

def toggle_auth(enable, user_id=None):
    """Toggle authentication feature flag"""
    env_vars = read_env_file()
    
    if enable:
        env_vars["ENABLE_AUTH"] = "true"
        print("✅ Authentication ENABLED")
        print("   - Users must login to access protected endpoints")
        print("   - JWT tokens will be validated")
    else:
        env_vars["ENABLE_AUTH"] = "false"
        print("🚫 Authentication DISABLED (Demo Mode)")
        print("   - All endpoints accessible without login")
        print("   - Demo user will be used automatically")
        
        if user_id:
            env_vars["AUTH_BYPASS_USER_ID"] = str(user_id)
            print(f"   - Using user ID {user_id} as demo user")
        elif "AUTH_BYPASS_USER_ID" in env_vars:
            print(f"   - Using existing bypass user ID: {env_vars['AUTH_BYPASS_USER_ID']}")
        else:
            print("   - Using default demo user (ID=1)")
    
    write_env_file(env_vars)
    
    # Show current status
    print(f"\n📋 Current Configuration:")
    print(f"   ENABLE_AUTH: {env_vars.get('ENABLE_AUTH', 'not set')}")
    print(f"   AUTH_BYPASS_USER_ID: {env_vars.get('AUTH_BYPASS_USER_ID', 'not set')}")
    
    print(f"\n🔄 Restart the backend to apply changes:")
    print(f"   - Railway: Changes will auto-deploy")
    print(f"   - Local: Restart your FastAPI server")

def show_status():
    """Show current auth status"""
    env_vars = read_env_file()
    
    print("🔍 Current Authentication Status:")
    print(f"   ENABLE_AUTH: {env_vars.get('ENABLE_AUTH', 'not set')}")
    print(f"   AUTH_BYPASS_USER_ID: {env_vars.get('AUTH_BYPASS_USER_ID', 'not set')}")
    
    if env_vars.get('ENABLE_AUTH') == 'false':
        print("\n🚫 Auth is DISABLED (Demo Mode)")
        print("   - No login required")
        print("   - Demo user access granted")
    else:
        print("\n✅ Auth is ENABLED")
        print("   - Login required for protected endpoints")
        print("   - JWT validation active")

def main():
    parser = argparse.ArgumentParser(description="Toggle authentication feature flag")
    group = parser.add_mutually_exclusive_group(required=True)
    
    group.add_argument("--enable", action="store_true", help="Enable authentication")
    group.add_argument("--disable", action="store_true", help="Disable authentication (demo mode)")
    group.add_argument("--status", action="store_true", help="Show current auth status")
    
    parser.add_argument("--user-id", type=int, help="User ID to use when auth is disabled")
    
    args = parser.parse_args()
    
    if args.status:
        show_status()
    elif args.enable:
        toggle_auth(enable=True, user_id=args.user_id)
    elif args.disable:
        toggle_auth(enable=False, user_id=args.user_id)

if __name__ == "__main__":
    main()
